---
- name: Create PVCs
  shell: |
    for x in {0..5}; do
    cat << EOF | kubectl apply -f -
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: gluster-pvc-${x}
    spec:
      accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    EOF
    done
  become: true
  become_user: "{{ install_user }}"
  register: pvc_create
- name: DEBUG
  debug:
    var: pvc_create
  when: debug_output == true
- name: Check PVCs
  shell: |
    kubectl get pvc
  become: true
  become_user: "{{ install_user }}"
  register: pvc_get
- name: Show PVCs
  debug:
    var: pvc_get
- name: Create example Deployment using PVC
  shell: |
    cat << EOF | kubectl apply -f -
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        run: demo-nginx
      name: demo-nginx
    spec:
      replicas: 1
      selector:
        matchLabels:
          run: demo-nginx
      template:
        metadata:
          labels:
            run: demo-nginx
        spec:
          containers:
          - image: nginx
            name: demo-nginx
            ports:
            - containerPort: 80
            volumeMounts:
            - name: demo-nginx-pvc
              mountPath: /usr/share/nginx/html
          volumes:
          - name: demo-nginx-pvc
            persistentVolumeClaim:
              claimName: gluster-pvc-1
      EOF
  become: true
  become_user: "{{ install_user }}"
  register: deployment_create
- name: DEBUG
  debug:
    var: deployment_create
  when: debug_output == true
- name: Check Deployment
  shell: |
    kubectl get pod -l run=demo-nginx
  become: true
  become_user: "{{ install_user }}"
  register: deployment_get
- name: Show Deployment
  debug:
    var: deployment_get