---
- name: Configure executor
  hosts: localhost
  vars_files: main.yml
  roles:
    - { role: generate-resources }
- name: Install and Configure Gluster
  hosts: ocne-worker
  vars_files: main.yml
  roles:
    - { role: install-configure-gluster }
